version: '3.1'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: db
    ports:
      - 3310:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 9005:80
    environment:
      - PMA_ARBITRARY=1