# Generated by Django 4.0.4 on 2022-04-28 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallonDor',
            fields=[
                ('year', models.IntegerField()),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='players.player')),
            ],
        ),
    ]
