name: Django CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
      uses: sonarsource/sonarcloud-github-action@master

  deploy-to-gcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'gcpdeploy-container-image'
      run: |
        gcloud config set project ballon-d-or-django-api-public
        gcloud builds submit --config=cloudbuild.yaml --substitutions=_DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
    - name: 'gcpdeploy-vm'
      run: |
        gcloud config set run/region us-central
        gcloud compute instances update-container ballon-d-or-vm --container-image gcr.io/ballon-d-or-django-api-public/ballon-d-or:latest